### ISSUE TITLE
Create environment

### ISSUE THREAD

**Issue by shapirogrill** [shapirogrill/backend-ideas-manager#1]
# TODO
- [x] Create a local and a CI profile
- [x] Update readme with commands
- [x] Create docker-compose file for database
