### ISSUE TITLE
Implement table creation

### ISSUE THREAD

**Issue by shapirogrill** [shapirogrill/backend-ideas-manager#13]
Since a table is created by a user, the app add rows in `UserTable` and `TableField` tables but the user table is not created yet in the db.

This issue should implement this feature.

# TODO:
- If a table is created with its fields : 
  - [x] Table and fields should be created using sql command
 - If a table is modified (only the name now) 
   - [x] Table name should be modified using sql command
 - If a table is deleted
   - [x] Table should be deleted using sql command.
